model: vllm
model_args:
  pretrained: openai/gpt-oss-120b
  dtype: auto
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9
  max_model_len: 131072
  chat_template_args:
    reasoning_effort: medium
batch_size: auto
apply_chat_template: true
predict_only: true
gen_kwargs:
  temperature: 1.0
  top_p: 1.0
  max_gen_toks: 131072
